# Generated by Django 4.0.4 on 2022-08-09 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recrutador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretecao_salarial', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutador.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_de_empresa', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('data_de_inicio', models.DateField()),
                ('data_de_saida', models.DateField(null=True)),
                ('obiservacao', models.CharField(blank=True, max_length=200)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=50)),
                ('data_de_inicio', models.DateField(blank=True)),
                ('data_de_termino', models.DateField(blank=True, null=True)),
                ('obiservacao', models.CharField(blank=True, max_length=200)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.candidato')),
            ],
        ),
    ]
