# Generated by Django 4.0.4 on 2022-08-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='experiencia',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='ultima_escolaridade',
        ),
    ]
