# Generated by Django 4.0.4 on 2022-08-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_remove_candidato_experiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencias',
            name='data_de_saida',
            field=models.DateField(null=True),
        ),
    ]
