# Generated by Django 4.0.4 on 2022-08-10 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recrutador', '0003_rename_pretencao_salarial_vaga_faixa_salarial'),
        ('candidato', '0002_candidato_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinhaIscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretecao_salarial', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutador.vaga')),
            ],
        ),
        migrations.RemoveField(
            model_name='escolaridade',
            name='candidato',
        ),
        migrations.RemoveField(
            model_name='experiencia',
            name='candidato',
        ),
        migrations.AddField(
            model_name='escolaridade',
            name='owner',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencia',
            name='owner',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Candidato',
        ),
    ]
