# Generated by Django 4.0.4 on 2022-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_minhaiscricao_remove_escolaridade_candidato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('segundo_nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=100)),
                ('pretecao_salarial', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='minhaiscricao',
            name='pretecao_salarial',
        ),
    ]
