# Generated by Django 4.0.4 on 2022-08-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_alter_experiencias_data_de_saida'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experiencias',
            new_name='Experiencia',
        ),
    ]
