# Generated by Django 4.0.4 on 2022-08-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empregador', '0001_initial'),
        ('candidato', '0004_rename_experiencias_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='vaga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empregador.vaga'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='escolaridade',
            name='candidato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidato.candidato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='candidato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candidato.candidato'),
            preserve_default=False,
        ),
    ]
