# Generated by Django 4.0.4 on 2022-08-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0005_alter_dadospessoais_pretecao_salarial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencia',
            old_name='nome_de_empresa',
            new_name='nome_da_empresa',
        ),
    ]
