# Generated by Django 4.0.4 on 2022-08-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0006_rename_nome_de_empresa_experiencia_nome_da_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospessoais',
            name='pretecao_salarial',
        ),
    ]
