# Generated by Django 4.0.4 on 2022-08-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0007_remove_dadospessoais_pretecao_salarial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PretencaoSalarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pretencao_salarial', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
