# Generated by Django 4.0.4 on 2022-08-09 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_vaga', models.CharField(max_length=50)),
                ('faixa_salarial', models.CharField(max_length=50)),
                ('escolaridade_minima', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
